export type ActivityTier = 'flagship' | 'alternate'
export type Availability = 'available' | 'maybe' | 'unavailable'

export interface Activity {
  id: string
  name: string
  category: string
  tier: ActivityTier
  estimate: string
  restriction: string
  seasonal: string
  sourceUrl: string
  note: string
}

export interface Itinerary {
  id: string
  name: string
  subtitle: string
  estimatedCost: string
  theme: string
  days: { label: string; stops: string[] }[]
}

export const activities: Activity[] = [
  { id: 'zero-g', name: 'Zero-G OR Skydiving', category: 'Bucket-list adrenaline', tier: 'flagship', estimate: '$299+ skydiving / Zero-G varies', restriction: 'Zero-G is a flight-specific booking; skydiving has age, weight, and medical requirements.', seasonal: 'Weather affects skydiving. Zero-G dates are limited.', sourceUrl: 'https://www.gozerog.com/', note: 'Mutually exclusive headline slot. Participants can choose their preferred option.' },
  { id: 'speedway', name: 'Texas Motor Speedway driving experience', category: 'Motorsports', tier: 'flagship', estimate: 'Varies by package', restriction: 'Driver age/license, waiver, and package rules apply.', seasonal: 'Schedule-dependent.', sourceUrl: 'https://www.texasmotorspeedway.com/', note: 'A high-energy alternative for the group.' },
  { id: 'six-flags', name: 'Six Flags Over Texas', category: 'Theme park', tier: 'flagship', estimate: 'Estimate: $45-$120', restriction: 'Ride restrictions apply.', seasonal: 'Best in spring/fall; check event calendar.', sourceUrl: 'https://www.sixflags.com/overtexas', note: 'Full-day option with varied intensity levels.' },
  { id: 'state-fair', name: 'State Fair of Texas + Texas Auto Show', category: 'Seasonal Texas event', tier: 'flagship', estimate: 'Admission: $7-$25; Estimate: $60-$150 all-in', restriction: 'Food, Midway rides, and parking are additional. Plan a full day and use DART or carpool for easier logistics.', seasonal: 'September 25-October 18, 2026 only. Future dates and pricing must be rechecked.', sourceUrl: 'https://bigtex.com/faq/', note: 'Big Tex, fair food, 100+ included attractions, 70 Midway rides, and the Texas Auto Show in one Texas-scale day.' },
  { id: 'scarborough', name: 'Scarborough Renaissance Festival', category: 'Seasonal Texas event', tier: 'flagship', estimate: '2027 price TBD', restriction: 'Groups of 15+ qualify for advance group tickets; 6-10 can use regular admission. Outdoor walking and all-day attendance.', seasonal: 'April 10-May 31, 2027; Saturdays, Sundays, and Memorial Day Monday.', sourceUrl: 'https://www.srfestival.com/', note: 'A full day of jousting, artisan craft, live entertainment, and willingly over-the-top participatory fun.' },
  { id: 'mustang-magic', name: 'Fort Worth Stock Show + Mustang Magic', category: 'Seasonal Texas event', tier: 'flagship', estimate: '2027 price TBD', restriction: 'Mustang Magic ticket includes Stock Show grounds admission, but not the rodeo or midway rides.', seasonal: 'Fort Worth Stock Show is held in January-February; confirm exact 2027 program dates.', sourceUrl: 'https://www.fwssr.com/p/horse-shows/mustang-magic', note: 'Previously wild mustangs compete in handling, maneuvers, and trail classes - a considerably rarer Texas experience.' },
  { id: 'goodguys', name: 'Goodguys Lone Star Nationals', category: 'Seasonal motorsports', tier: 'alternate', estimate: '2026 price TBD', restriction: 'A spectator car and truck show; confirm ticket and parking terms before committing.', seasonal: 'Currently scheduled for October 2-3, 2026 at Texas Motor Speedway.', sourceUrl: 'https://www.texasmotorspeedway.com/media/news/texas-motor-speedway-announces-action-packed-2026-schedule.html', note: 'An easy fit for anyone who appreciates custom cars, trucks, hot rods, and the Texas Motor Speedway setting.' },
  { id: 'nascar-weekend', name: 'NASCAR Tripleheader Weekend', category: 'Seasonal motorsports', tier: 'alternate', estimate: '2027 ticket price TBD', restriction: 'Ticket packages and exact event-day schedules must be confirmed before booking.', seasonal: 'Currently announced for April 30-May 2, 2027 at Texas Motor Speedway.', sourceUrl: 'https://www.texasmotorspeedway.com/media/news/texas-motor-speedway-announces-action-packed-2026-schedule.html', note: 'A dedicated race-weekend anchor with all three national NASCAR series at the same track.' },
  { id: 'stockyards', name: 'Fort Worth Stockyards + rodeo', category: 'Texas original', tier: 'flagship', estimate: 'Estimate: $30-$100', restriction: 'Rodeo ticketing and show dates vary.', seasonal: 'Year-round; rodeo schedule varies.', sourceUrl: 'https://www.fortworthstockyards.com/', note: 'Cattle drive, historic district, and a Texas-scale evening.' },
  { id: 'gun-experience', name: 'Texas Gun Experience', category: 'Shooting experience', tier: 'flagship', estimate: 'Varies by firearm/package', restriction: 'Government ID, waivers, safety rules, and range eligibility apply.', seasonal: 'Year-round indoor.', sourceUrl: 'https://texasgunexperience.com/', note: 'A step up from a standard pistol-range outing.' },
  { id: 'mountain-bike', name: 'Grapevine Lake mountain-bike rental + Northshore Trail', category: 'Outdoor adventure', tier: 'alternate', estimate: '$65 hardtail / $95 full-suspension daily rental', restriction: 'Trail condition must be checked before riding; Northshore has beginner-to-difficult segments and closes to bikes when wet or muddy.', seasonal: 'Year-round; best in cooler, dry weather.', sourceUrl: 'https://www.bikemart.com/pages/bike-rentals', note: 'Rent proper trail bikes and ride Grapevine Lake\'s Northshore Trail - a legitimate lakeside mountain-bike outing, not a paved loop.' },
  { id: 'helicopter-tour', name: 'Downtown Dallas helicopter tour', category: 'Bucket-list aerial', tier: 'flagship', estimate: '$225 per person at two passengers; $175 for a third, before fees', restriction: 'Maximum 280 lb per passenger and 600 lb combined. Weather and airspace can change routes; tours run in groups of 2-3.', seasonal: 'Year-round, weather permitting. Multiple flights are needed for 6-10 people.', sourceUrl: 'https://www.skyhelicopters.com/request-a-downtown-dallas-tour', note: 'A 30-minute city flight over landmarks including Reunion Tower, downtown, Fair Park, White Rock Lake, and Love Field.' },
  { id: 'ifly', name: 'iFLY Indoor Skydiving', category: 'Indoor adrenaline', tier: 'alternate', estimate: 'Current offer: $141 per flyer; group package varies', restriction: 'Wear lace-up sneakers and comfortable clothes; no loose items. Group packages and private sessions are available.', seasonal: 'Year-round indoor; Frisco.', sourceUrl: 'https://www.iflyworld.com/dallas', note: 'The accessible adrenaline alternative when real skydiving is too weather-sensitive, expensive, or intimidating.' },
  { id: 'activate', name: 'Activate Games Southlake', category: 'Interactive competition', tier: 'alternate', estimate: '$20.99-$38.99 per person', restriction: 'Physical and puzzle-based game rooms; choose a duration that matches the group\'s energy level.', seasonal: 'Year-round indoor.', sourceUrl: 'https://playactivate.com/en/southlake', note: 'A light-up active-gaming facility built around jumping, climbing, laser-dodging, and team problem-solving.' },
  { id: 'ebike-tour', name: 'Dallas electric bike or scooter tour', category: 'City exploration', tier: 'alternate', estimate: '$49.99+ e-bike / $59.99+ scooter tour', restriction: 'Riders must be 16+ with a valid driver\'s license; closed-toe shoes required.', seasonal: 'Year-round; use morning or sunset times in hot weather.', sourceUrl: 'https://incitywheels.com/', note: 'A guided two-hour way to see Dallas neighborhoods without a bus-tour feel; private/custom tours are available.' },
  { id: 'museum-illusions', name: 'Museum of Illusions Dallas', category: 'Interactive museum', tier: 'alternate', estimate: 'Price varies by timed ticket', restriction: 'Timed tickets recommended; group visits can be arranged directly with the museum.', seasonal: 'Year-round indoor; downtown Dallas.', sourceUrl: 'https://moidallas.com/group-visits/', note: 'A fast, visual, photo-friendly reset with hands-on optical-illusion exhibits.' },
  { id: 'sixth-floor', name: 'The Sixth Floor Museum at Dealey Plaza', category: 'Texas history', tier: 'flagship', estimate: '$24 online / $27 onsite adult admission, plus $1 online fee', restriction: 'Timed tickets are sold in limited intervals; allow at least 90 minutes. Large bags are restricted.', seasonal: 'Year-round; Wednesday-Sunday.', sourceUrl: 'https://tickets.jfk.org/webstore/shop/ViewItems.aspx?C=GA&CG=OT', note: 'The essential serious-history option: Kennedy\'s life, assassination, and legacy inside the former Texas School Book Depository.' },
  { id: 'go-ape', name: 'Go Ape Plano zipline + ropes course', category: 'Outdoor adventure', tier: 'alternate', estimate: 'Price varies by course and date', restriction: 'Treetop Adventure requires age 10+ and 4 ft 7 in; enclosed shoes, waiver, and advance booking recommended.', seasonal: 'Year-round; weather/daylight affect availability.', sourceUrl: 'https://www.goape.com/location/Texas-Plano/', note: 'A 2-3 hour course with rope ladders, suspended obstacles, Tarzan swings, and ziplines above Oak Point Park.' },
  { id: 'att-stadium-tour', name: 'AT&T Stadium tour', category: 'Texas sports landmark', tier: 'alternate', estimate: 'Price varies by tour type', restriction: 'Field and locker-room access vary by event schedule. Book ahead; field access is not guaranteed.', seasonal: 'Daily tours, subject to blackout dates and events.', sourceUrl: 'https://attstadium.com/tours/', note: 'See the Cowboys\' stadium as architecture, contemporary-art collection, and sports shrine - with field access when available.' },
  { id: 'reunion-tower', name: 'Reunion Tower GeO-Deck', category: 'Dallas landmark', tier: 'alternate', estimate: '$19-$40 adult admission', restriction: 'Timed ticket required. Guided tours max at 10 guests; group discounts begin at 15.', seasonal: 'Year-round; best near sunset or with a day-and-night ticket.', sourceUrl: 'https://reuniontower.com/plan-your-visit/', note: 'A low-friction skyline stop with indoor/outdoor 360-degree views from 470 feet up.' },
  { id: 'chapel-thanksgiving', name: 'Chapel of Thanks-Giving + Thanks-Giving Square', category: 'Dallas landmark', tier: 'alternate', estimate: 'Free', restriction: 'The chapel is a quiet, reverent space; visit respectfully. Check same-day hours before going.', seasonal: 'Year-round; garden is generally open daily, while chapel hours are more limited.', sourceUrl: 'https://www.thanksgiving.org/visit-the-square', note: 'A surprising, architecturally distinctive downtown reset: a spiraling non-denominational chapel in a public garden.' },
  { id: 'national-videogame-museum', name: 'National Videogame Museum', category: 'Interactive museum', tier: 'flagship', estimate: '$12 adult admission', restriction: 'Tickets are sold at the museum ticket window. Allow time for playable exhibits and the arcade.', seasonal: 'Year-round indoor; Frisco.', sourceUrl: 'https://nvmusa.org/tickets-membership/', note: 'A hands-on, nostalgia-heavy museum with playable history, an 80s bedroom recreation, and a retro arcade.' },
  { id: 'escape-game', name: 'The Escape Game Grapevine', category: 'Interactive competition', tier: 'alternate', estimate: 'From $39 per person for groups', restriction: 'One room accommodates 2-8; a group of 9-16 is split into two parallel rooms, making this a good 6-10-person matchup.', seasonal: 'Year-round indoor; Grapevine.', sourceUrl: 'https://theescapegame.com/grapevine/parties-and-events/', note: 'A polished, cinematic escape-room challenge that becomes more fun when teams race each other in parallel rooms.' },
  { id: 'las-colinas-gondola', name: 'Las Colinas gondola cruise', category: 'Dallas-area original', tier: 'alternate', estimate: 'From $155 per private gondola; 6-10-person package price TBD', restriction: 'Confirm the specific boat capacity and private-group package before booking; advance reservations required.', seasonal: 'Year-round; weather permitting. Sunset is especially appealing.', sourceUrl: 'https://irving.gondola.com/', note: 'An unexpectedly transportive private cruise through the Mandalay Canals - more memorable than a standard dinner reservation.' },
  { id: 'arboretum', name: 'Dallas Arboretum + seasonal evening program', category: 'Outdoor culture', tier: 'alternate', estimate: '$21.95-$25.95 adult admission, plus $15 parking per vehicle', restriction: 'Evening programming is not continuous; confirm the current calendar and ticket terms before building an itinerary around it.', seasonal: 'Year-round gardens; evening events and major displays are seasonal.', sourceUrl: 'https://www.dallasarboretum.org/visit/general-garden-admission/', note: 'A scenic White Rock Lake outing that works especially well when a seasonal evening concert, festival, or lighted display is on the calendar.' },
  { id: 'katy-trail', name: 'Katy Trail ride + Uptown stop', category: 'City exploration', tier: 'alternate', estimate: 'Free with your own bike; rental cost TBD', restriction: 'The 3.5-mile trail is public; coordinate rentals separately and ride defensively around pedestrians.', seasonal: 'Year-round; mornings and sunset are best in hot weather.', sourceUrl: 'https://katytraildallas.org/', note: 'An easy, flexible outdoor activity through Uptown that pairs naturally with coffee, lunch, or a nearby dinner.' },
  { id: 'buc-ees', name: "Buc-ee's Texas road-trip stop", category: 'Texas original', tier: 'alternate', estimate: 'Estimate: $15-$40 for food and snacks', restriction: 'Choose the location and route after the trip anchor is selected; this is a stop, not a standalone day activity.', seasonal: 'Year-round; best as a drive-day or between-city detour.', sourceUrl: 'https://buc-ees.com/', note: 'Beaver nuggets, jerky, Texas-branded everything, and the kind of oversized roadside stop that out-of-state guests remember.' },
  { id: 'fowling', name: 'Fowling Warehouse DFW', category: 'Interactive competition', tier: 'alternate', estimate: 'Price varies by lane reservation', restriction: 'A reserved lane accommodates up to 10 players. Confirm availability and required waiver details directly with the venue.', seasonal: 'Year-round indoor; Plano.', sourceUrl: 'https://fowlingwarehouse.com/', note: 'Football bowling: throw a football at bowling pins in a fast-moving team game that needs almost no explanation.' },
  { id: 'future-flight', name: 'Future Flight powered-parachute adventure', category: 'Bucket-list aerial', tier: 'alternate', estimate: '$99 20-minute dual intro lesson / $199 50-minute adventure flight', restriction: 'Participants must be 18+. Flights are weather-dependent; each rider flies with an instructor, so schedule rotations for 6-10.', seasonal: 'Year-round, weather permitting; calmer morning or evening conditions are generally preferable.', sourceUrl: 'https://flyppc.com/ppc-flights', note: 'A surprisingly accessible open-air flight for the group members who want a personal aerial adventure without committing to skydiving.' },
  { id: 'horseback', name: 'Stockyards Stables horseback ride', category: 'Outdoor Texas', tier: 'alternate', estimate: 'Price varies by ride and group booking', restriction: 'Rider requirements, weight limits, waiver, and group capacity must be confirmed with the stable.', seasonal: 'Year-round; weather permitting.', sourceUrl: 'https://fortworthstockyards.com/', note: 'Turn a Stockyards visit into an actual horseback outing rather than simply walking the historic district.' },
  { id: 'smash-n-bash', name: 'Smash N Bash rage room', category: 'Indoor adrenaline', tier: 'alternate', estimate: 'Average about $45 per person; packages begin at $89 per room', restriction: 'Only four people may be in a smash room at once, so a 6-10-person group rotates. Follow waiver and protective-gear rules.', seasonal: 'Year-round indoor; check location availability.', sourceUrl: 'https://smashnbash.com/faqs/', note: 'A controlled deconstruction-room outing for the group that finds breaking old appliances surprisingly therapeutic.' },
  { id: 'summit-climbing', name: 'Summit climbing gym session', category: 'Indoor adventure', tier: 'alternate', estimate: 'Day-pass and instruction cost TBD', restriction: 'First-time climbers need a waiver and should confirm orientation, belay instruction, and current group-booking policies.', seasonal: 'Year-round indoor.', sourceUrl: 'https://summitgyms.com/', note: 'A physical, social challenge where novices can start on bouldering walls while more experienced climbers take on ropes.' },
  { id: 'battlefield-nerf', name: 'Battlefield Nerf War Arena', category: 'Interactive competition', tier: 'alternate', estimate: 'Price and current schedule TBD', restriction: 'Confirm group availability, waivers, age policy, and booking terms before presenting it as a committed option.', seasonal: 'Indoor; availability must be reconfirmed.', sourceUrl: 'https://feverup.com/m/91779', note: 'A large indoor Nerf-battle concept in Denton that could be a high-energy group favorite if current sessions and private bookings are available.' },
  { id: 'meow-wolf', name: 'Meow Wolf Grapevine', category: 'Immersive experience', tier: 'flagship', estimate: 'Estimate: $35-$55', restriction: 'Timed entry recommended.', seasonal: 'Year-round indoor.', sourceUrl: 'https://meowwolf.com/visit/grapevine', note: 'A surreal, interactive indoor reset between bigger events.' },
  { id: 'medieval-times', name: 'Medieval Times', category: 'Dinner show', tier: 'flagship', estimate: 'Estimate: $70-$100', restriction: 'Advance group reservations advised.', seasonal: 'Year-round; performance schedule varies.', sourceUrl: 'https://www.medievaltimes.com/plan-your-trip/dallas-tx', note: 'A dinner-and-show anchor with zero nightlife dependency.' },
  { id: 'lonesome-dove', name: 'Lonesome Dove Western Bistro', category: 'Flagship dining', tier: 'flagship', estimate: 'Estimate: $90-$160 food, tax, and tip', restriction: 'Reserve ahead. Private dining begins at 12, so 6-10 should use a standard reservation.', seasonal: 'Year-round; Stockyards location.', sourceUrl: 'https://www.lonesomedovefortworth.com/menus', note: 'Chef Tim Love\'s upscale Western cooking and wild-game menu make this the strongest food pairing for a Stockyards night.' },
  { id: 'the-mexican', name: 'The Mexican', category: 'Flagship dining', tier: 'flagship', estimate: 'Estimate: $90-$170 food, tax, and tip', restriction: 'Reserve ahead. Its Don Roberto private room seats 10; Oaxaca handles up to 14.', seasonal: 'Year-round; Dallas Design District.', sourceUrl: 'https://themexicandallas.com/private-dining-luxurymexican', note: 'A high-design Mexican fine-dining experience with a private room that is unusually well matched to this group size.' },
  { id: 'fearings', name: "Fearing's at The Ritz-Carlton", category: 'Flagship dining', tier: 'flagship', estimate: 'Estimate: $110-$190 food, tax, and tip', restriction: 'Reservations recommended; private dining options are available.', seasonal: 'Year-round; Uptown Dallas.', sourceUrl: 'https://www.fearingsrestaurant.com/our-menus', note: 'Chef Dean Fearing\'s polished Southwestern/Texas cooking is the refined special-occasion choice.' },
  { id: 'pappas-bros', name: 'Pappas Bros. Steakhouse', category: 'Flagship dining', tier: 'flagship', estimate: 'Estimate: $125-$225 food, tax, and tip', restriction: 'Reserve ahead. Private rooms begin above this group size, but standard reservations work for 6-10.', seasonal: 'Year-round; Dallas.', sourceUrl: 'https://www.pappasbros.com/location/?id=92', note: 'A classic, high-service steakhouse option when the group wants one unambiguously excellent dinner.' },
  { id: 'cattlemens', name: "Cattlemen's Steakhouse", category: 'Texas dining', tier: 'alternate', estimate: 'Estimate: $55-$110 food, tax, and tip', restriction: 'Reserve ahead for a weekend Stockyards dinner.', seasonal: 'Year-round; Fort Worth Stockyards.', sourceUrl: 'https://cattlemenssteakhouse.com/', note: 'A historic Stockyards steakhouse that is more casual than the flagship dinners but deeply on-theme.' },
  { id: 'whataburger', name: 'Whataburger', category: 'Budget dining', tier: 'alternate', estimate: 'Estimate: $10-$20', restriction: 'Use mobile ordering or split into smaller orders to avoid a long wait for a 6-10 person group.', seasonal: 'Year-round; many Dallas and Fort Worth locations.', sourceUrl: 'https://locations.whataburger.com/tx.html', note: 'The intentionally cheap, easy arrival or departure meal - a useful counterweight to the premium experiences.' },
  { id: 'uptown-eats', name: 'Uptown Eats trolley + walking food tour', category: 'Food tour', tier: 'alternate', estimate: '$110 per person', restriction: '2.5-hour tour with some walking and steep trolley steps; historic trolleys are not wheelchair accessible.', seasonal: 'Friday-Sunday, subject to tour availability.', sourceUrl: 'https://www.visitdallas.com/events/uptown-eats-trolley-walking-tour/', note: 'A street-food-style progressive meal through Uptown, with multiple tastings, a vintage trolley ride, and behind-the-scenes trolley-barn access.' },
  { id: 'moviehouse-eatery', name: 'Moviehouse & Eatery', category: 'Dinner + movie', tier: 'alternate', estimate: 'Ticket and meal cost varies by showtime and menu', restriction: 'Reserve adjacent recliners early for 6-10. In-theater food service is available during the movie.', seasonal: 'Year-round indoor; locations and film schedule vary.', sourceUrl: 'https://www.cinepolisusa.com/mckinney/theater-details/', note: 'An easy, comfortable dinner-and-movie option with full waiter service and a real menu rather than a standard multiplex counter.' },
  { id: 'andretti', name: 'Andretti Indoor Karting & Games', category: 'Indoor competition', tier: 'alternate', estimate: 'Varies by attraction', restriction: 'Attraction height/age rules apply.', seasonal: 'Year-round indoor.', sourceUrl: 'https://www.andrettikarting.com/', note: 'Alternate only, not a flagship activity.' },
  { id: 'fossil-rim', name: 'Fossil Rim Wildlife Center', category: 'Outdoor Texas', tier: 'alternate', estimate: 'Estimate: $30-$40', restriction: 'Vehicle and reservation policies apply.', seasonal: 'Most comfortable in cooler weather.', sourceUrl: 'https://fossilrim.org/', note: 'An unusual day trip for the outdoors-oriented itinerary.' },
]

export const itineraries: Itinerary[] = [
  { id: 'premium', name: 'Premium Split Adventure', subtitle: 'Bucket-list centerpiece, games, and Texas history.', estimatedCost: 'Estimate: $500-$1,500+ before lodging', theme: 'Big swing / premium', days: [
    { label: 'Day 1', stops: ['National Videogame Museum', 'Game-show-style team competition', 'Dinner at Puttery'] },
    { label: 'Day 2', stops: ['Zero-G OR Skydiving', 'Medieval Times dinner show'] },
    { label: 'Day 3', stops: ['Bureau of Engraving and Printing', 'Stockyards cattle drive', 'Fort Worth rodeo'] },
  ] },
  { id: 'adrenaline', name: 'Shared Adrenaline + Firepower', subtitle: 'A high-energy weekend with a Texas finish.', estimatedCost: 'Estimate: $350-$900 before lodging', theme: 'High shared intensity', days: [
    { label: 'Day 1', stops: ['Six Flags Over Texas', 'Coyote Drive-In'] },
    { label: 'Day 2', stops: ['Skydiving', 'Texas Gun Experience'] },
    { label: 'Day 3', stops: ['Bureau of Engraving and Printing', 'Stockyards and rodeo'] },
  ] },
  { id: 'outdoor', name: 'Outdoor Texas Weekend', subtitle: 'Lake time, trail time, horses, and a flexible closer.', estimatedCost: 'Estimate: $250-$600 before lodging', theme: 'Outdoor / lower logistics', days: [
    { label: 'Day 1', stops: ['Fort Worth Nature Center hike', 'Stockyard Stables horseback ride', 'Fort Worth rodeo'] },
    { label: 'Day 2', stops: ['Lewisville Lake jet skis or tritoon', 'Coyote Drive-In'] },
    { label: 'Day 3', stops: ['BEP + National Videogame Museum OR Texas Gun Experience'] },
  ] },
]

export const candidateDates = ['2026-09-18', '2026-09-19', '2026-09-20', '2026-10-02', '2026-10-03', '2026-10-04', '2026-10-16', '2026-10-17', '2026-10-18']
